project:
  type: website
  output-dir: docs

website:
  title: "quarto-testsite"
  description: "This is a test website to try out Quarto."

  navbar:

    right:
      - text: "home"
        href: index.qmd
      - text: "about"
        href: about.qmd
      - text: "blog"
        href: blog.qmd
      - text: "projects"
        file: projects/index.qmd
      - text: "tutorials"
        file: tutorials/index.qmd

  sidebar:
    - title: "tutorials"
      style: docked
      collapse-level: 1
      contents: tutorials
    - title: "projects"
      contents:
        - projects/index.qmd
        - projects/project1.qmd
        - projects/project2.qmd
        - projects/project3.qmd
        - projects/project4.qmd
  
  page-footer: 
    left: "Copyright 2023, test"
    right: 
      - icon: github
        href: https://github.com/
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/
        aria-label: twitter
      - icon: youtube
        href: https://www.youtube.com/
        aria-label: YouTube

format:
  html:
    theme: vapor
    css: styles.css
    toc: true



