project:
  type: website
  output-dir: docs

website:
  title: "quarto-testsite"
  description: "This is a test website to try out Quarto."
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
    left:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/
        aria-label: twitter
      - icon: youtube
        href: https://www.youtube.com/
        aria-label: YouTube
  
  page-footer: 
    left: "Copyright 2023, test"
    right: 
      - icon: github
        href: https://github.com/
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/
        aria-label: twitter
      - icon: youtube
        href: https://www.youtube.com/
        aria-label: YouTube

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



